trigger:
  branches:
    include:
      - dev
      - staging
      - prod

pr:
  - dev
  - staging
  - prod

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  isDev: $[eq(variables['Build.SourceBranchName'], 'dev')]
  isStg: $[eq(variables['Build.SourceBranchName'], 'staging')]
  isProd: $[eq(variables['Build.SourceBranchName'], 'prod')]
  vmImageName: 'ubuntu-18.04'

stages:
- stage: Build_elixir_codebox_app_Dev
  displayName: Build app and test
  condition: eq(variables.isDev, true)

  jobs:
    - job: Run_Test_For_Dev
      displayName: Run_Test_For_Dev
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: CmdLine@2
        displayName: 'Install asdf into the vm'
        inputs:
          script: |
            sudo apt-get update
            sudo apt install -y postgresql-client
            echo "Postgres client installed"
            echo "downloading asdf from git"
            git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.0
            echo "installing the asdf"
            . $HOME/.asdf/asdf.sh
            . $HOME/.asdf/completions/asdf.bash
            echo "Install asdf plugin dependecies"
            sudo apt-get install dirmngr gpg curl gawk
            echo "Install asdf plugins"
            asdf plugin add erlang
            asdf plugin add elixir

      - task: DownloadSecureFile@1
        name: TestExs
        displayName: 'test.exs file'
        inputs:
          secureFile: 'test.exs'
      - task: DownloadSecureFile@1
        name: DevExs
        displayName: 'dev.exs file'
        inputs:
          secureFile: 'dev.exs'
      - task: CmdLine@2
        displayName: 'Copy the test.exs to Project directory'
        inputs:
          script: |
              cp $(TestExs.secureFilePath) '$(System.DefaultWorkingDirectory)/config'
              cp $(DevExs.secureFilePath) '$(System.DefaultWorkingDirectory)/config'

      - task: CmdLine@2
        displayName: 'Install elixir and erlang using asdf'
        inputs:
          script: |
            . $HOME/.asdf/asdf.sh
            . $HOME/.asdf/completions/asdf.bash
            asdf install

      - task: CmdLine@2
        displayName: 'Fetch and Install project dependencies for test'
        inputs:
          script: |
            . $HOME/.asdf/asdf.sh
            . $HOME/.asdf/completions/asdf.bash
            mix local.hex --force && mix local.rebar --force
            echo "Package manager **done**"
            mix deps.get --only test
            echo "app dependencies installed **done**"

      - task: CmdLine@2
        displayName: 'Run test for codebox dev'
        inputs:
          script: |
            . $HOME/.asdf/asdf.sh
            . $HOME/.asdf/completions/asdf.bash
            echo "**Running tests**"
            mix test

    - job: Run_DB_migration
      displayName: Run_DB_migration
      dependsOn: Run_Test_For_Dev
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: CmdLine@2
        displayName: 'Install asdf into the vm'
        inputs:
          script: |
            sudo apt-get update
            echo "downloading asdf from git"
            git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.0
            echo "installing the asdf"
            . $HOME/.asdf/asdf.sh
            . $HOME/.asdf/completions/asdf.bash
            echo "Install asdf plugin dependecies"
            sudo apt-get install dirmngr gpg curl gawk
            echo "Install asdf plugins"
            asdf plugin add erlang
            asdf plugin add elixir

      - task: DownloadSecureFile@1
        name: DevExs
        displayName: 'dev.exs file'
        inputs:
          secureFile: 'dev.exs'

      - task: DownloadSecureFile@1
        name: ProdExs
        displayName: 'prod.exs file'
        inputs:
          secureFile: 'prod.exs'

      - task: CmdLine@2
        displayName: 'Copy the dev, prod, test.exs to Project directory'
        inputs:
          script: |
              cp $(DevExs.secureFilePath) '$(System.DefaultWorkingDirectory)/config'
              cp $(ProdExs.secureFilePath) '$(System.DefaultWorkingDirectory)/config'

      - task: CmdLine@2
        displayName: 'Install elixir and erlang using asdf'
        inputs:
          script: |
            . $HOME/.asdf/asdf.sh
            . $HOME/.asdf/completions/asdf.bash
            asdf install

      - task: CmdLine@2
        displayName: 'Fetch and Install project dependencies for dev'
        inputs:
          script: |
            . $HOME/.asdf/asdf.sh
            . $HOME/.asdf/completions/asdf.bash
            mix local.hex --force && mix local.rebar --force
            echo "Package manager **done**"
            mix deps.get --only dev
            echo "app dependencies installed **done**"

      - task: CmdLine@2
        displayName: 'Run codebox migration'
        inputs:
          script: |
            . $HOME/.asdf/asdf.sh
            . $HOME/.asdf/completions/asdf.bash
            echo "**Running migration to dev db**"
            chmod +x deployments/scripts/db_migrations.sh
            ./db_migrations.sh

    - job: Run_deploy_codebox_image_dev_to_registry
      displayName: Run_deploy_codebox_image_dev_to_registry
      depensOn: Run_DB_migration
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: DownloadSecureFile@1
        name: DevExs
        displayName: 'dev.exs file'
        inputs:
          secureFile: 'dev.exs'
      - task: CmdLine@2
        displayName: 'Copy the test.exs to Project directory'
        inputs:
          script: |
              cp $(TestExs.secureFilePath) '$(System.DefaultWorkingDirectory)/config'
              cp $(DevExs.secureFilePath) '$(System.DefaultWorkingDirectory)/config'

      - task: CmdLine@2
        displayName: 'Install AWS cli into the machine'
        inputs:
          script: |
              echo "Installing AWS dependencies"
              sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              sudo unzip awscliv2.zip
              sudo ./aws/install
              echo "Copying Dockerfile to source directory"
              echo "Set AWS configure"
              aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
              aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
              aws configure set region $(AWS_DEFAULT_REGION)

      - task: CmdLine@2
        displayName: 'Build and Push codebox image to AWS ECR.'
        inputs:
          script: |
              aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin public.ecr.aws/p9t2s4l2
              docker build -t codebox-dev .
              docker tag codebox-dev:$(tag) public.ecr.aws/p9t2s4l2/codebox-dev:$(tag)
              docker push public.ecr.aws/p9t2s4l2/codebox-dev:$(tag)
              #aws ecs update-service --cluster firma-api --service firma-user-service --force-new-deployment

#######################################################################################################################

- stage: Build_codebox_app_Prod
  displayName: Run Db migration, build image and deploy
  condition: eq(variables.isProd, true)
  jobs:
    - job: Run_deploy_codebox_image_prod_to_registry
      displayName: Run_deploy_codebox_image_dev_to_registry
      pool:
        vmImage: $(vmImageName)
      steps:

      - task: DownloadSecureFile@1
        name: DevExs
        displayName: 'dev.exs file'
        inputs:
          secureFile: 'dev.exs'

      - task: DownloadSecureFile@1
        name: ProdExs
        displayName: 'prod.exs file'
        inputs:
          secureFile: 'prod.exs'

      - task: CmdLine@2
        displayName: 'Copy the prod.exs to Project directory'
        inputs:
          script: |
              cp $(ProdExs.secureFilePath) '$(System.DefaultWorkingDirectory)/config'
              cp $(DevExs.secureFilePath) '$(System.DefaultWorkingDirectory)/config'

      - task: CmdLine@2
        displayName: 'Install AWS cli into the machine'
        inputs:
          script: |
              echo "Installing AWS dependencies"
              sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              sudo unzip awscliv2.zip
              sudo ./aws/install
              echo "Copying Dockerfile to source directory"
              echo "Set AWS configure"
              aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
              aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
              aws configure set region $(AWS_DEFAULT_REGION)

      - task: CmdLine@2
        displayName: 'Build and Push codebox prod image to AWS ECR.'
        inputs:
          script: |
              aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin public.ecr.aws/p9t2s4l2
              docker build -t codebox-prod .
              docker tag codebox-prod:$(tag) public.ecr.aws/p9t2s4l2/codebox-prod:$(tag)
              docker push public.ecr.aws/p9t2s4l2/codebox-prod:$(tag)
              #aws ecs update-service --cluster firma-api --service firma-user-service --force-new-deployment


       
